env:
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
rules:
  indent: ['error', 4]
  "@typescript-eslint/indent": off
  max-len: ['error', 80]
  max-lines-per-function: ['error', 25]
  max-lines: ['error', 250]

