name: "packages.python"

on:
  push:
    paths:
      - packages/python/**
      - .github/workflows/packages.python.yaml
jobs:
  lintAndTest:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/python
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Validate schema
        working-directory: ${{env.working-directory}}
        run: bash ./scripts/schema-validate.sh
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          python -m pip install --upgrade pip pipenv==2023.7.23
          python -m pipenv install --dev --system
      - name: Lint
        working-directory: ${{env.working-directory}}
        run: |
          black --check --diff --color .
          flake8 .
          mypy --color --pretty .
      - name: Test
        working-directory: ${{env.working-directory}}
        run: |
          coverage run -m pytest --color=yes .
          coverage xml
          coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: packages/python
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to CodeClimate
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          workingDirectory: packages/python
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_TOKEN}}
  publish:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/python
    strategy:
      fail-fast: false
    needs: ['lintAndTest']
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install build tools
        run: pip install build
      - name: Build package
        working-directory: ${{env.working-directory}}
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: packages/python/dist/
