name: "lint & test & publish"

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        if: ${{ github.ref_type == 'tag' }}
        run: npm run build
      - name: publish
        if: ${{ github.ref_type == 'tag' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
